services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    network_mode: host
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: Postgres_7002754372
      POSTGRES_DB: dokploy
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "Redis_7002754372"
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
